project_id = "tuxvwpgwnnozubdpskhr"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54329
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://tuxvwpgwnnozubdpskhr.supabase.co/auth/v1/callback"]
jwt_expiry = 3600

[realtime]
enabled = true
port = 54330

[functions]
enabled = true
port = 54331

[functions.create-user]
verify_jwt = true